### ISSUE TITLE
Add info about controller and mk to score player

### ISSUE THREAD

**Issue by stLmpp** [stLmpp/biomercs-api#35]
Front-end: https://github.com/stLmpp/biomercs-ng/issues/50

- [x] new entity Controller, columns: id, name
- [x] new column idController in the ScorePLayer entity
- [x] new properties idController and controllerName in the ScorePlayerViewModel
- [x] new column idController in the Player entity, this will be the default in the ScorePlayerViewModel, if the player does not set it and submiting a score

**Comment by karinamelo26** [comment]
Closed by https://github.com/stLmpp/biomercs-v2-api/commit/4d9efd6a50e144f70ec022dcf1984b6e9a1b0aca
